service: project-manager-probot 

custom:
  stage:
  - staging
  - production

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: staging
  environment: ${file(config/${opt:stage, self:provider.stage}.env.yml)}

package:
    exclude:
        - events/**
        - docs/**
        - package-lock.json

functions:
  webhook:
    handler: lib/handlers/webhook.probot
    events:
      - http:
          path: /webhooks
          method: post

